services:
  defindex-soroban:
    image: esteblock/soroban-preview:21.0.1@sha256:b2345967694194c07bc35e03f584788eff95e973659daa3f8ce324fdc621ca13
    container_name: defindex-soroban
    volumes:
      - ./apps/contracts:/workspace
    ipc: host
    networks:
      - defindex-network
    command: tail -f /dev/null

  stellar:
    image: stellar/quickstart:v426-latest-amd64@sha256:274395daab6fa8033b9213f152d56699358917fb01d7c7e95392a37fc00c9d01
    container_name: stellar
    networks:
      - defindex-network
    ports:
      - "8000:8000"
    command: --local --enable-soroban-rpc --enable-soroban-diagnostic-events
    stdin_open: true
    tty: true

networks:
  defindex-network:
    driver: bridge
